version: '3.11'
services:
  backend:
    build: .
    container_name: backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - postgres-db
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    networks:
      - db_network

  postgres-db:
    image: 'postgres:15'
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - db_network

volumes:
  postgres-data:

networks:
  db_network:
    driver: bridge